version: 2
updates:
  - package-ecosystem: "github-actions"
    open-pull-requests-limit: 10
    directories:
      - "/"
      - "/.github/actions/*"
    schedule:
      interval: "daily"
    cooldown:
      default-days: 2
    labels:
      - "dependencies"
      - "bot"
