# https://docs.zizmor.sh/configuration/
rules:
  # rule does not apply to reusable worfklows where permissions are defined by the caller workflow
  excessive-permissions:
    ignore:
      - list-commits.yml
      - pr-assign-author.yml
      - releases-json.yml
      - zizmor.yml
