# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Install k3s'
description: 'GitHub Action composite to install k3s'

inputs:
  version:
    description: 'k3s version. (e.g, v1.29.0+k3s1)'
    required: true
    default: 'v1.29.0+k3s1'

runs:
  using: "composite"
  steps:
    -
      run: |
        export KUBECONFIG=${RUNNER_TEMP}/.kube/config
        mkdir -p "${KUBECONFIG}"
        echo "KUBECONFIG=${KUBECONFIG}" >> $GITHUB_ENV
        set -x
        curl -sfL https://get.k3s.io | sh -s - server --docker --disable-network-policy --disable traefik --disable metrics-server --flannel-backend=none --write-kubeconfig-mode 666 --write-kubeconfig ${KUBECONFIG} || journalctl -xeu k3s.service --no-pager
        sudo k3s kubectl get node
      env:
        INSTALL_K3S_VERSION: ${{ inputs.version }}
      shell: bash
