# https://help.github.com/en/articles/metadata-syntax-for-github-actions
name: 'Install k3s'
description: 'GitHub Action composite to install k3s'

inputs:
  version:
    description: 'k3s version. (e.g, v1.29.0+k3s1)'
    required: true
    default: 'v1.29.0+k3s1'

runs:
  using: "composite"
  steps:
    -
      run: |
        set -x
        curl -sfL https://get.k3s.io | sh -s - server --docker --disable-network-policy --disable traefik --disable metrics-server --flannel-backend=none --write-kubeconfig-mode 666 || journalctl -xeu k3s.service --no-pager
        sudo k3s kubectl get node

        kubeConfig=${RUNNER_TEMP}/.kube/config
        mkdir -p "${RUNNER_TEMP}/.kube"
        echo "KUBECONFIG=${kubeConfig}" >> $GITHUB_ENV
        sudo cat /etc/rancher/k3s/k3s.yaml > "${kubeConfig}"
        chmod 600 "${kubeConfig}"
      env:
        INSTALL_K3S_VERSION: ${{ inputs.version }}
      shell: bash
