name: zizmor

on:
  workflow_call:
    inputs:
      path:
        required: false
        type: string
        default: .
      version:
        required: false
        type: string
      collect:
        required: false
        type: string
      min-severity:
        required: false
        type: string
      min-confidence:
        required: false
        type: string
      persona:
        required: false
        type: string
      offline:
        required: false
        type: boolean
        default: false
      no-online-audits:
        required: false
        type: boolean
        default: false
      strict-collection:
        required: false
        type: boolean
        default: false

jobs:
  zizmor:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      -
        name: Setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          enable-cache: false
      -
        name: Install zizmor
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_VERSION: ${{ inputs.version }}
        with:
          script: |
            const inpVersion = core.getInput('version');
            await exec.exec('uv', ['tool', 'install', `zizmor${inpVersion ? `@${inpVersion}` : ''}`]);
      -
        name: Run zizmor
        id: zizmor
        uses: actions/github-script@3a2844b7e9c422d3c10d287c895573f7108da1b3 # v9.0.0
        env:
          INPUT_PATH: ${{ inputs.path }}
          INPUT_COLLECT: ${{ inputs.collect }}
          INPUT_MIN-SEVERITY: ${{ inputs.min-severity }}
          INPUT_MIN-CONFIDENCE: ${{ inputs.min-confidence }}
          INPUT_PERSONA: ${{ inputs.persona }}
          INPUT_OFFLINE: ${{ inputs.offline }}
          INPUT_NO-ONLINE-AUDITS: ${{ inputs.no-online-audits }}
          INPUT_STRICT-COLLECTION: ${{ inputs.strict-collection }}
          GH_TOKEN: ${{ github.token }}
        with:
          script: |
            const fs = require('fs');
            const os = require('os');
            const path = require('path');

            const inpPath = core.getInput('path');
            const inpCollect = core.getMultilineInput('collect');
            const inpMinSeverity = core.getInput('min-severity');
            const inpMinConfidence = core.getInput('min-confidence');
            const inpPersona = core.getInput('persona');
            const inpOffline = core.getBooleanInput('offline');
            const inpNoOnlineAudits = core.getBooleanInput('no-online-audits');
            const inpStrictCollection = core.getBooleanInput('strict-collection');

            const args = ['--format=sarif', '--color=always'];
            for (const item of inpCollect) {
              args.push(`--collect=${item}`);
            }
            if (inpMinSeverity) {
              args.push(`--min-severity=${inpMinSeverity}`);
            }
            if (inpMinConfidence) {
              args.push(`--min-confidence=${inpMinConfidence}`);
            }
            if (inpPersona) {
              args.push(`--persona=${inpPersona}`);
            }
            if (inpOffline) {
              args.push('--offline');
            }
            if (inpNoOnlineAudits) {
              args.push('--no-online-audits');
            }
            if (inpStrictCollection) {
              args.push('--strict-collection');
            }
            args.push(inpPath);

            const exitCodeMessage = {
              1: 'error during audit, consult zizmor output',
              2: 'argument parsing failure, consult zizmor output',
              3: 'no inputs were collected',
              11: 'findings detected, highest severity is informational',
              12: 'findings detected, highest severity is low',
              13: 'findings detected, highest severity is medium',
              14: 'findings detected, highest severity is high'
            };

            const res = await exec.getExecOutput('zizmor', args, {
              ignoreReturnCode: true
            });
            if (res.exitCode > 0 && res.exitCode < 11) {
              const details = exitCodeMessage[res.exitCode] || 'unexpected exit code, consult zizmor output';
              core.setFailed(`zizmor exited with code ${res.exitCode}: ${details}`);
              return;
            }

            const sarifPath = path.join(fs.mkdtempSync(path.join(process.env.RUNNER_TEMP || os.tmpdir(), 'zizmor-')), 'results.sarif');
            await fs.writeFileSync(sarifPath, res.stdout.trim());
            core.setOutput('sarif-path', sarifPath);
      -
        name: Upload SARIF report
        if: ${{ always() && steps.zizmor.outputs.sarif-path != '' }}
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        with:
          sarif_file: ${{ steps.zizmor.outputs.sarif-path }}
          category: zizmor
